# Generated by Django 6.0.1 on 2026-01-09 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disease'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='predictions/'),
            preserve_default=False,
        ),
    ]
